### ISSUE TITLE
No need to wait after Wire.requestFrom().

### ISSUE THREAD

**Issue by Koepel** [ckanibal/InertialSensors#1]
In the files "register.cpp" and "compass.cpp" you may remove the while-loops to wait for something after a Wire.requestFrom().
Explanation: [Common-mistakes#1](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes#1)

**Comment by ckanibal** [comment]
I never imagined anybody would actually use this! 
Thank you for the comment, you are absolutely right. Fixed it.
